version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/var/www/html
      - ./env.dev:/var/www/html/.env
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_DSN: ${REDIS_DSN}
      APP_SECRET: ${APP_SECRET}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

